package com.hwserve.still;
import com.hwserve.still.shared.R;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.content.res.Configuration;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.time.LocalDate;

public final class MainActivity extends Activity {
 private final Handler handler=new Handler(Looper.getMainLooper());
 private TimerEngine engine;
 private boolean watch,dark;
 private int bg,fg,muted,surface,accent=Color.rgb(85,185,141),page=0;
 private LinearLayout root,body;
 private TextView clock,status,dots,play,summary;
 private final Runnable tick=new Runnable(){public void run(){engine=new TimerEngine(MainActivity.this);if(engine.state.due(SystemClock.elapsedRealtime())){engine.command("tick");engine=new TimerEngine(MainActivity.this);}if(page==0)refresh();handler.postDelayed(this,250);}};
 private final BroadcastReceiver changes=new BroadcastReceiver(){public void onReceive(Context c,Intent i){engine=new TimerEngine(c);if(page==0)refresh();else if(page==1)draw();}};
 @Override public void onCreate(Bundle b){super.onCreate(b);watch=getResources().getBoolean(R.bool.watch_ui)||getPackageManager().hasSystemFeature("android.hardware.type.watch");if(b!=null)page=b.getInt("page",0);engine=new TimerEngine(this);engine.command("tick");draw();}
 @Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putInt("page",page);}
 @Override public void onResume(){super.onResume();engine=new TimerEngine(this);draw();if(Build.VERSION.SDK_INT>=33)registerReceiver(changes,new IntentFilter(TimerEngine.CHANGED),Context.RECEIVER_NOT_EXPORTED);else registerReceiver(changes,new IntentFilter(TimerEngine.CHANGED));handler.post(tick);}
 @Override public void onPause(){super.onPause();handler.removeCallbacks(tick);unregisterReceiver(changes);}
 @Override public void onBackPressed(){if(page!=0){page=0;draw();}else super.onBackPressed();}
 private int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setFontFeatureSettings("tnum");return t;}
 private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 private void draw(){int theme=engine.prefs.getInt("theme",0);dark=watch||theme==2||(theme==0&&(getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)==Configuration.UI_MODE_NIGHT_YES);accent=Color.parseColor(dark?"#55B98D":"#2F865F");bg=Color.parseColor(dark?"#101413":"#FAFBF8");fg=Color.parseColor(dark?"#F1F5F1":"#1C2923");muted=Color.parseColor(dark?"#8D9B93":"#748379");surface=Color.parseColor(dark?"#1C2420":"#EEF2EB");getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(watch?View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY:(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR));if(engine.prefs.getBoolean("screen",false))getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);else getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
 root=column();root.setBackgroundColor(bg);root.setPadding(dp(watch?16:28),dp(watch?12:12),dp(watch?16:28),dp(watch?12:18));setContentView(root);
 if(!watch){LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView brand=text("still",24,fg);brand.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);brand.setTypeface(Typeface.create("sans-serif-medium",0));top.addView(brand,new LinearLayout.LayoutParams(0,dp(52),1));TextView note=text("ONE MOMENT AT A TIME",10,muted);note.setLetterSpacing(.12f);top.addView(note);root.addView(top);}
 body=column();root.addView(body,new LinearLayout.LayoutParams(-1,0,1));if(page==0)timer();else if(page==1)statistics();else settings();
 if(!watch){LinearLayout nav=new LinearLayout(this);String[] names={"◷  타이머","▥  기록","⚙  설정"};for(int i=0;i<3;i++){final int tab=i;TextView t=text(names[i],14,i==page?accent:muted);t.setBackground(shape(i==page?surface:bg,18));nav.addView(t,new LinearLayout.LayoutParams(0,dp(52),1));t.setOnClickListener(v->{page=tab;draw();});}root.addView(nav);}}
 private void timer(){if(watch){TextView more=text("still  ·  설정",12,muted);body.addView(more,new LinearLayout.LayoutParams(-1,dp(24)));more.setOnClickListener(v->{page=2;draw();});}else body.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));
 status=text("집중",watch?13:16,accent);body.addView(status,new LinearLayout.LayoutParams(-1,dp(watch?20:36)));clock=text("25:00",watch?40:88,fg);clock.setTypeface(Typeface.create("sans-serif-light",0));clock.setLetterSpacing(-.045f);clock.setAutoSizeTextTypeUniformWithConfiguration(24,watch?40:88,1,android.util.TypedValue.COMPLEX_UNIT_SP);body.addView(clock,new LinearLayout.LayoutParams(-1,dp(watch?50:132)));dots=text("○ ○ ○ ○",watch?14:19,accent);dots.setLetterSpacing(watch?.15f:.3f);if(watch)dots.setAutoSizeTextTypeUniformWithConfiguration(8,14,1,android.util.TypedValue.COMPLEX_UNIT_SP);body.addView(dots,new LinearLayout.LayoutParams(-1,dp(watch?20:42)));
 LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);TextView reset=text("↺",watch?22:28,muted);reset.setContentDescription("현재 타이머 초기화");controls.addView(reset,new LinearLayout.LayoutParams(dp(watch?44:68),dp(watch?44:72)));reset.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("현재 타이머를 초기화할까요?").setMessage("완료한 집중 기록은 유지돼요.").setNegativeButton("취소",null).setPositiveButton("초기화",(d,n)->command("reset")).show());play=text("▶",watch?23:28,Color.parseColor(dark?"#10271B":"#FFFFFF"));play.setBackground(shape(accent,100));controls.addView(play,new LinearLayout.LayoutParams(dp(watch?44:76),dp(watch?44:76)));play.setOnClickListener(v->{permissions();command("toggle");});TextView skip=text("›|",watch?20:24,muted);skip.setContentDescription("현재 회차 건너뛰기");controls.addView(skip,new LinearLayout.LayoutParams(dp(watch?44:68),dp(watch?44:72)));skip.setOnClickListener(v->command("skip"));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(watch?48:94));cp.topMargin=dp(watch?0:24);body.addView(controls,cp);
 if(!watch){TextView hint=text("지금은, 한 가지에만.",14,muted);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,dp(42));hp.topMargin=dp(26);body.addView(hint,hp);body.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));summary=text("",13,muted);body.addView(summary,new LinearLayout.LayoutParams(-1,dp(48)));}refresh();}
 private void refresh(){if(clock==null)return;clock.setText(TimerEngine.format(engine.state.left(SystemClock.elapsedRealtime())));status.setText(engine.label()+(engine.state.running?"":engine.state.remaining<engine.state.duration?" · 일시정지":" · 준비"));StringBuilder d=new StringBuilder();for(int i=0;i<engine.state.cycle;i++)d.append(i<engine.state.completed?"● ":"○ ");dots.setText(d.toString().trim());dots.setContentDescription("집중 "+engine.state.completed+"회 완료, "+engine.state.cycle+"회 후 긴 휴식");play.setText(engine.state.running?"Ⅱ":"▶");play.setContentDescription(engine.state.running?"일시정지":"시작");if(!watch&&summary!=null){int[] s=engine.stats(LocalDate.now().toString());summary.setText("오늘  "+s[0]+"회 집중  ·  "+s[1]+"분");}}
 private void command(String a){engine=new TimerEngine(this);engine.command(a);engine=new TimerEngine(this);refresh();}
 private void permissions(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},1);if(Build.VERSION.SDK_INT>=31&&!getSystemService(AlarmManager.class).canScheduleExactAlarms())new AlertDialog.Builder(this).setTitle("정확한 종료 알림").setMessage("타이머가 제시간에 알려주도록 알람 권한을 켜주세요.").setPositiveButton("설정 열기",(d,n)->startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM).setData(android.net.Uri.parse("package:"+getPackageName())))).setNegativeButton("나중에",null).show();}
 @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] results){super.onRequestPermissionsResult(code,permissions,results);if(code==1){if(results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)engine.command("tick");else Toast.makeText(this,"종료 알림을 받으려면 설정에서 알림을 허용해주세요",Toast.LENGTH_LONG).show();}}
 private LinearLayout scroll(String title){ScrollView s=new ScrollView(this);s.setFillViewport(true);body.addView(s,new LinearLayout.LayoutParams(-1,-1));LinearLayout list=column();s.addView(list);TextView heading=text(title,watch?18:30,fg);heading.setGravity(watch?Gravity.CENTER:Gravity.LEFT);heading.setTypeface(Typeface.create("sans-serif-medium",0));list.addView(heading,new LinearLayout.LayoutParams(-1,dp(watch?36:72)));if(watch){TextView back=text("‹ 타이머",13,accent);list.addView(back,new LinearLayout.LayoutParams(-1,dp(36)));back.setOnClickListener(v->{page=0;draw();});}return list;}
 private void section(LinearLayout list,String title){TextView t=text(title,12,accent);t.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(44));lp.topMargin=dp(14);list.addView(t,lp);}
 private void setting(LinearLayout list,String title,String value,Runnable click){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView label=text(title,watch?13:16,fg);label.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);row.addView(label,new LinearLayout.LayoutParams(0,-1,1));TextView val=text(value+"  ›",watch?12:15,muted);row.addView(val);list.addView(row,new LinearLayout.LayoutParams(-1,dp(watch?48:58)));row.setOnClickListener(v->click.run());}
 private void duration(LinearLayout list,String title,String key,int def){setting(list,title,engine.prefs.getInt(key,def)+"분",()->{NumberPicker picker=new NumberPicker(this);picker.setMinValue(1);picker.setMaxValue(180);picker.setValue(engine.prefs.getInt(key,def));new AlertDialog.Builder(this).setTitle(title).setView(picker).setNegativeButton("취소",null).setPositiveButton("저장",(d,n)->{engine.prefs.edit().putInt(key,picker.getValue()).apply();engine=new TimerEngine(this);boolean fresh=!engine.state.running&&engine.state.remaining==engine.state.duration;boolean same=(key.equals("focus")&&engine.state.mode==0)||(key.equals("short")&&engine.state.mode==1)||(key.equals("long")&&engine.state.mode==2);if(fresh&&same){engine.state.duration=picker.getValue()*60_000L;engine.state.remaining=engine.state.duration;engine.command("tick");}draw();}).show();});}
 private void toggle(LinearLayout list,String title,String key,boolean def){Switch s=new Switch(this);s.setText(title);s.setTextSize(watch?12:15);s.setTextColor(fg);s.setChecked(engine.prefs.getBoolean(key,def));list.addView(s,new LinearLayout.LayoutParams(-1,dp(watch?52:58)));s.setOnCheckedChangeListener((v,on)->{engine.prefs.edit().putBoolean(key,on).apply();if(key.equals("screen"))draw();});}
 private String version(){try{return getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(PackageManager.NameNotFoundException e){return "";}}
 private void settings(){LinearLayout list=scroll("설정");section(list,"타이머");duration(list,"집중 시간","focus",25);duration(list,"짧은 휴식","short",5);duration(list,"긴 휴식","long",15);setting(list,"긴 휴식까지",engine.prefs.getInt("cycle",4)+"회",()->new AlertDialog.Builder(this).setTitle("긴 휴식까지").setSingleChoiceItems(new String[]{"2회","3회","4회","5회","6회","7회","8회"},engine.prefs.getInt("cycle",4)-2,(d,n)->{engine.prefs.edit().putInt("cycle",n+2).apply();d.dismiss();engine=new TimerEngine(this);draw();}).setNegativeButton("취소",null).show());section(list,"다음 회차");toggle(list,"휴식 자동 시작","autoBreak",false);toggle(list,"집중 자동 시작","autoFocus",false);section(list,"종료 알림");toggle(list,"소리","sound",true);toggle(list,"진동","vibration",true);setting(list,"시스템 알림 설정","열기",()->startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName())));section(list,"화면");if(!watch)setting(list,"테마",new String[]{"시스템","라이트","다크"}[engine.prefs.getInt("theme",0)],()->new AlertDialog.Builder(this).setTitle("테마").setSingleChoiceItems(new String[]{"시스템","라이트","다크"},engine.prefs.getInt("theme",0),(d,n)->{engine.prefs.edit().putInt("theme",n).apply();d.dismiss();draw();}).setNegativeButton("취소",null).show());toggle(list,"화면 켜두기","screen",false);if(watch)setting(list,"집중 기록","보기",()->{page=1;draw();});TextView foot=text("Still "+version()+" · 오롯이 집중\n기록은 이 기기에만 저장돼요.",12,muted);foot.setPadding(0,dp(30),0,dp(30));list.addView(foot);}
 private void statistics(){LinearLayout list=scroll("집중 기록");LocalDate today=LocalDate.now();int[] s=engine.stats(today.toString());section(list,"오늘");TextView total=text(s[1]+"분",watch?36:56,fg);total.setTypeface(Typeface.create("sans-serif-light",0));list.addView(total);TextView count=text(s[0]+"번의 작은 집중",14,muted);list.addView(count,new LinearLayout.LayoutParams(-1,dp(42)));section(list,"최근 7일");int[] values=new int[7];for(int i=0;i<7;i++)values[i]=engine.stats(today.minusDays(6-i).toString())[1];list.addView(new WeekChart(this,values),new LinearLayout.LayoutParams(-1,dp(watch?110:210)));section(list,"하루씩, 차곡차곡");for(int i=0;i<7;i++){LocalDate day=today.minusDays(i);int[] v=engine.stats(day.toString());setting(list,day.getMonthValue()+"월 "+day.getDayOfMonth()+"일",v[0]+"회 · "+v[1]+"분",()->{});}}
 private final class WeekChart extends View{final int[] values;final Paint p=new Paint(3);WeekChart(Context c,int[] v){super(c);values=v;setContentDescription("최근 일주일의 집중 시간 막대 그래프");}protected void onDraw(Canvas c){int max=25;for(int v:values)max=Math.max(max,v);float cell=getWidth()/7f,height=getHeight()-dp(40);for(int i=0;i<7;i++){float x=cell*i+cell*.24f;p.setColor(surface);c.drawRoundRect(x,dp(12),x+cell*.52f,height,dp(7),dp(7),p);float h=(height-dp(12))*values[i]/max;p.setColor(accent);if(values[i]>0)c.drawRoundRect(x,height-h,x+cell*.52f,height,dp(7),dp(7),p);p.setColor(muted);p.setTextSize(dp(11));p.setTextAlign(Paint.Align.CENTER);c.drawText(String.valueOf(LocalDate.now().minusDays(6-i).getDayOfMonth()),cell*(i+.5f),height+dp(24),p);}}}
}
